### PR TITLE
[TRUS-4155] - Update Settlor heading to Will settlor

### PR DESCRIPTION
**Pull request by jassalrichy**
Before:

Draft copy of the trust’s declaration - Register and Maintain a Trust - GOV UK

After:

Draft copy of the trust’s declaration - Register and Maintain a Trust - GOV UK

### CODE REVIEW

**Comment by jackheslop96** [comment]
@jassalrichy could you update the Welsh message as well? Suspect we’ll have ‘deceased settlor’ translated somewhere

**Comment by jassalrichy** [comment]
@jackheslop96 Can't find an existing one, so will need to send off to WLU:

https://github.com/search?q=org%3Ahmrc+%22Deceased+settlor%22+extension%3A.en&type=Code

**Comment by jackheslop96** [comment]
@jassalrichy fair enough. I suppose an alternative could be to go with 'Will settlor' which is what we have referred to a deceased settlor as elsewhere in the service e.g. https://github.com/hmrc/maintain-settlors-frontend/blob/cc51314716a60f2ad487c1777aad2b2e42134dfd/conf/messages.en#L52

**Comment by adamconder** [comment]
I think Will Settlor is a good suggestion as it is what is on the add to pages.

**Pull request merged**
